MvcStok/MvcStok/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori

        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(int sayfa=1)
        {
            //var degerler = db.tbl_Kategoriler.ToList();

            var degerler = db.tbl_Kategoriler.ToList().ToPagedList(sayfa,4);

            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }
        [HttpPost]

        public ActionResult YeniKategori(tbl_Kategoriler p1)
        {
            if(!ModelState.IsValid)
            {
                return View("YeniKategori");
            }

            db.tbl_Kategoriler.Add(p1);
            db.SaveChanges();
            return View();

        }

        public ActionResult Sil(int id)
        {
            var kategori = db.tbl_Kategoriler.Find(id);
            db.tbl_Kategoriler.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriGetir(int id)
        {
            var ktg = db.tbl_Kategoriler.Find(id);

            return View("KategoriGetir", ktg);
        }

        public ActionResult Guncelle(tbl_Kategoriler p1) 
        {
            var ktg = db.tbl_Kategoriler.Find(p1.KategoriID);
            ktg.KategoriAd = p1.KategoriAd;
            db.SaveChanges();
            return RedirectToAction("Index");

        
        }
    }
}

MvcStok/MvcStok/Views/Kategori/Index.cshtml
@using MvcStok.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<tbl_Kategoriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<table class="table table-bordered">
    <tr>
        <th> KATEGORİ ID </th>
        <th> KATEGORİ ADI </th>
        <th> SİL </th>
        <th> GÜNCELLE </th>

    </tr>
    <tbody>
        @foreach(var ktg in Model) 
            
            {
                <tr>
                    <th>@ktg.KategoriID</th>
                    <td>@ktg.KategoriAd</td>
                    <td><a href="/Kategori/Sil/@ktg.KategoriID" class="btn btn-danger"><i class="fa fa-trash"></i> </a> </td>
                    <td><a href="/Kategori/KategoriGetir/@ktg.KategoriID/" class="btn btn-success"><i class="fa fa-refresh"> </i> </a> </td>
                </tr>

            }
    </tbody>
</table>

@Html.PagedListPager((IPagedList)Model,sayfa=>Url.Action("Index", new {sayfa}))

<a href="/Kategori/YeniKategori/" class="btn btn-primary"> YENİ KATEGORİ EKLE </a> 

MvcStok/MvcStok/Views/Kategori/KategoriGetir.cshtml
@model MvcStok.Models.Entity.tbl_Kategoriler
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle","Kategori", FormMethod.Post))
            
{
    <div class="form-group">

        @Html.LabelFor(m => m.KategoriID)
        @Html.TextBoxFor(m => m.KategoriID, new { @class = "form-control" })
        <br>
        @Html.LabelFor(m => m.KategoriAd)
        @Html.TextBoxFor(m => m.KategoriAd, new { @class = "form-control" })

    </div>

    <div>
        <button class="btn btn-warning"> KATEGORİ GÜNCELLE </button>

    </div>
}

MvcStok/MvcStok/Views/Kategori/YeniKategori.cshtml
@model MvcStok.Models.Entity.tbl_Kategoriler
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">

    @*<div>

            <label> Kategori Adı </label>
            <input type="text" class="form-control" name="KategoriAd" />

        </div>*@

    <div>
        <label> Kategori Adı </label>
        @Html.TextBoxFor(m=>m.KategoriAd, new {@class="form-control"})
        @Html.ValidationMessageFor(m=>m.KategoriAd,"", new {@style="color:red"})
    </div>



        <div style="margin-top:15px">

            <button class="btn btn-info"> Kategori Ekle </button>

        </div>

</form>