MvcStok/MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri

        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(string p)
        {
            //var degerler = db.tbl_Musteriler.ToList();

            //return View(degerler);

            var degerler = from d in db.tbl_Musteriler select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MusteriAd.Contains(p));
            }
                return View(degerler.ToList());
        }

        [HttpGet]

        public ActionResult YeniMusteri()

        {
            return View();
        }

        [HttpPost]

        public ActionResult YeniMusteri(tbl_Musteriler p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.tbl_Musteriler.Add(p1);
            db.SaveChanges();
            return View();
        }

        public ActionResult Sil(int id)
        {
            var musteri = db.tbl_Musteriler.Find(id);
            db.tbl_Musteriler.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var musteri = db.tbl_Musteriler.Find(id);
            return View("MusteriGetir", musteri);
        }

        public ActionResult Guncelle(tbl_Musteriler p1)
        {
            var musteri = db.tbl_Musteriler.Find(p1.MusteriID);
            musteri.MusteriAd = p1.MusteriAd;
            musteri.MusteriSoyad = p1.MusteriSoyad;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

MvcStok/MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@model List<tbl_Musteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@using (Html.BeginForm("Index", "Musteri", FormMethod.Get))
            {
                <p> <b>Ara</b> : @Html.TextBox("p") 
                <input type="submit" value="Ara" />
                </p>
            }

<table class="table table-bordered">
    <tr>
        <th>MÜŞTERİ ID</th>
        <th>MÜŞTERİ ADI</th>
        <th>MÜŞTERİ SOYADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>ALERT SİL</th>
    </tr>
    <tbody>
        @foreach (var musteri in Model)
        {
            <tr>
                <th>@musteri.MusteriID</th>
                <td>@musteri.MusteriAd</td>
                <td>@musteri.MusteriSoyad</td>
                <td><a href="/Musteri/Sil/@musteri.MusteriID" class="btn btn-danger"><i class="fa fa-trash"></i> </a> </td>
                <td><a href="/Musteri/MusteriGetir/@musteri.MusteriID/" class="btn btn-success"><i class="fa fa-refresh"> </i> </a> </td>
                <td>@Html.ActionLink("SİL", "Sil", new { id=musteri.MusteriID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyor Musunuz?')"})</td>
            </tr>
        }
    </tbody>

</table>

<a href="/Musteri/YeniMusteri/" class="btn btn-primary"> YENİ MÜŞTERİ EKLE </a>

MvcStok/MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.tbl_Musteriler
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MusteriID)
        @Html.TextBoxFor(m => m.MusteriID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MusteriAd)
        @Html.TextBoxFor(m => m.MusteriAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MusteriSoyad)
        @Html.TextBoxFor(m => m.MusteriSoyad, new { @class = "form-control" })
    </div>

    <div>
        <button class="btn btn-warning"> MÜŞTERİ GÜNCELLE </button>
    </div>

}

MvcStok/MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.tbl_Musteriler
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">

    @*<div>
            <label> Müşteri Adı </label>
            <input type="text" class="form-control" name="MusteriAd" />
        </div>

        <div>
            <label> Müşteri Soyadı </label>
            <input type="text" class="form-control" name="MusteriSoyad" />
        </div>*@

    <div>
        <label> Müşteri Adı </label>
        @Html.TextBoxFor(m => m.MusteriAd, new { @class = "form-control"})
        @Html.ValidationMessageFor(m => m.MusteriAd, "", new { @style = "color:red" })
    </div>
    <div>
        <label> Müşteri Soyadı </label>
        @Html.TextBoxFor(m => m.MusteriSoyad, new { @class = "form-control"})
        @Html.ValidationMessageFor(m => m.MusteriSoyad, "", new { @style = "color:red" })
    </div>



    <div style="margin-top:15px">
        <button class="btn btn-info" id="btn1"> MÜŞTERİ EKLE </button>
    </div>
    
    <script>        
        $('#btn').click(function () {
            alert('Müşteri Ekleme İşlemi Yapıldı...');
        });  
    </script>


</form>