MvcStok/MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        MvcDbStokEntities db = new MvcDbStokEntities();

        public ActionResult Index()
        {
            var degerler = db.tbl_Urunler.ToList();

            return View(degerler);
        }

        [HttpGet]

        public ActionResult YeniUrun()

        {
            List<SelectListItem> degerler = (from i in db.tbl_Kategoriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KategoriAd,
                                                 Value = i.KategoriID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }

        [HttpPost]

        public ActionResult YeniUrun(tbl_Urunler p1)
        {
            var ktg = db.tbl_Kategoriler.Where(m => m.KategoriID == p1.tbl_Kategoriler.KategoriID).FirstOrDefault();
            p1.tbl_Kategoriler = ktg;

            db.tbl_Urunler.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var urun = db.tbl_Urunler.Find(id);
            db.tbl_Urunler.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            var urun = db.tbl_Urunler.Find(id);

            List<SelectListItem> degerler = (from i in db.tbl_Kategoriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KategoriAd,
                                                 Value = i.KategoriID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;

            return View("UrunGetir", urun);

        }

        public ActionResult Guncelle(tbl_Urunler p)
        {
            var urun = db.tbl_Urunler.Find(p.UrunID);
            urun.UrunAd = p.UrunAd;
            //urun.UrunKategori = p.UrunKategori;
            urun.Fiyat = p.Fiyat;
            urun.Stok = p.Stok;
            var ktg = db.tbl_Kategoriler.Where(m => m.KategoriID == p.tbl_Kategoriler.KategoriID).FirstOrDefault();
            urun.UrunKategori = ktg.KategoriID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.Entity
@model List<tbl_Urunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>ÜRÜN ID</th>
            <th>ÜRÜN ADI</th>
            <th>MARKASI</th>
            <th>KATEGORİ</th>
            <th>FİYAT</th>
            <th>STOK</th>
            <th> SİL </th>
            <th> GÜNCELLE </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var urun in Model)
        {
            <tr>
                <th>@urun.UrunID</th>
                <td>@urun.UrunAd</td>
                <td>@urun.Marka</td>
                <td>@urun.UrunKategori</td>
                <td>@urun.Fiyat</td>
                <td>@urun.Stok</td>
                <td><a href="/Urun/Sil/@urun.UrunID" class="btn btn-danger"> <i class="fa fa-trash"></i> </a> </td>
                <td><a href="/Urun/UrunGetir/@urun.UrunID/" class="btn btn-success"> <i class="fa fa-refresh"> </i> </a> </td>
            </tr>
        }
    </tbody>
</table>
<a href="/Urun/YeniUrun/" class="btn btn-primary"> YENİ ÜRÜN EKLE </a>

<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-colvis-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/sc-1.4.2/se-1.2.2/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#tbl1').DataTable({
            language: {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
            }
        });
    });
</script>
<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />

MvcStok/MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.tbl_Urunler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.UrunID)
        @Html.TextBoxFor(m => m.UrunID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.UrunAd)
        @Html.TextBoxFor(m => m.UrunAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.Marka)
        @Html.TextBoxFor(m => m.Marka, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.UrunKategori)
        @Html.DropDownListFor(m => m.tbl_Kategoriler.KategoriID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })

        @*@Html.TextBoxFor(m => m.Urunkategori,new {@class="form-control"})*@
        <br />
        @Html.LabelFor(m => m.Fiyat)
        @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.Stok)
        @Html.TextBoxFor(m => m.Stok, new { @class = "form-control" })
        <br />

    </div>
    <div>
        <button class="btn btn-warning">Ürün Güncelle</button>
    </div>
}

MvcStok/MvcStok/Views/Urun/YeniUrun.cshtml
@model MvcStok.Models.Entity.tbl_Urunler
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">

    <div>
        <label> Ürün Adı </label>
        <input type="text" class="form-control" name="UrunAd" required="" maxlength="30" placeholder="Ürün Adı Giriniz..."/>
    </div>
    <div>
        <label> Marka </label>
        <input type="text" class="form-control" name="Marka" required="" maxlength="30" placeholder="Marka Adı Giriniz..."/>
    </div>
    <div>
        <label> Kategori Seçiniz </label>
        @Html.DropDownListFor(m=> m.tbl_Kategoriler.KategoriID, (List<SelectListItem>) ViewBag.dgr, new { @class="form-control"})
    </div>
    <div>
        <label> Fiyat </label>
        <input type="number" min="0" class="form-control" name="Fiyat" required="" placeholder="Fiyatı Giriniz..."/>
    </div>
    <div>
        <label> Stok </label>
        <input type="number" min="0" max="10000"class="form-control" name="Stok" required="" placeholder="Stok Adedini Giriniz..."/>
    </div>


    <div style="margin-top:15px">

        <button class="btn btn-info"> Ürün Ekle </button>

    </div>

</form>